[workspace]
members = ["avmux"]
resolver = "2"

[workspace.package]
authors = ["Louis <836250617@qq.com>"]
license = "MIT"
edition = "2024"
repository = "https://github.com/kingwingfly/avmux"
documentation = "https://docs.rs/avmux"

[workspace.dependencies]
avmux = { path = "avmux" }

[profile.release]
lto = "fat"
opt-level = 3
codegen-units = 1
strip = "debuginfo"
panic = "abort"
