[workspace]
members = ["av_merge"]
resolver = "2"

[workspace.package]
version = "0.0.1"
authors = ["Louis <836250617@qq.com>"]
description = ""
license = "MIT"
edition = "2021"
repository = "https://github.com/kingwingfly/av_merge"
documentation = "https://docs.rs/av_merge"

[workspace.dependencies]
av_merge = { path = "av_merge" }
# async
tokio = { version = "1", default-features = false }

[profile.release]
lto = "fat"
opt-level = 3
codegen-units = 1
strip = "debuginfo"
panic = "abort"
