[package]
name = "av_merge"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "A crate to merge video and audio based on rsmpeg (dynamic link with ffmpeg lib)."

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
tokio = { workspace = true, features = ["rt-multi-thread", "signal", "macros"] }
