[package]
name = "avmux"
version = "0.2.4"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "A crate to merge video and audio based on rsmpeg (dynamic link with ffmpeg lib)."

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
rsmpeg = { version = "0.18.0", default-features = false }
bon = { version = "3.7" }
thiserror = "2.0"

[features]
default = ["link_system_ffmpeg", "ffmpeg8"]

ffmpeg8 = ["rsmpeg/ffmpeg8"]
ffmpeg7_1 = ["rsmpeg/ffmpeg7_1"]
ffmpeg7 = ["rsmpeg/ffmpeg7"]
ffmpeg6 = ["rsmpeg/ffmpeg6"]
link_system_ffmpeg = ["rsmpeg/link_system_ffmpeg"]
link_vcpkg_ffmpeg = ["rsmpeg/link_vcpkg_ffmpeg"]
