[package]
name = "avmux"
version = "0.1.2"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "A crate to merge video and audio based on rsmpeg (dynamic link with ffmpeg lib)."

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
rsmpeg = { version = "0.17.0" }
terrors = { version = "0.3.3" }

[target.'cfg(target_os = "macos")'.dependencies]
rsmpeg = { version = "0.17.0", features = ["link_system_ffmpeg"] }

[target.'cfg(target_os = "linux")'.dependencies]
rsmpeg = { version = "0.17.0", features = ["link_system_ffmpeg"] }
